services:
  serving:
    build:
      context: .
      target: serving-develop
    env_file:
      - .env
    user: "${UID}:${GID}"
    userns_mode: "host"
    volumes:
      - type: bind
        source: ./models
        target: /models
      #- ./models:/models:z
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ["${GPU_DEVICE}"]
              capabilities: [ gpu ]
    shm_size: 8GB

  develop:
    build:
      context: .
      target: util
      args:
        UID: ${UID}
        GID: ${GID}
    user: "${UID}:${GID}"
    userns_mode: "host"
    command: [ "./entrypoint.sh"]
    working_dir: /workspace/koina
    volumes:
      - .:/workspace/koina/:z
    env_file:
      - .env
