services:
  serving:
    ports:
      - 8500:8500
    build:
      context: .
      target: develop
    command: /models/start_triton_server.sh
    volumes:
      - ./models:/models
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    shm_size: 2GB
    restart: unless-stopped

  develop:
    build:
     context: .
     target: util
     args:
      UID: ${UID}
      GID: ${GID}
    user: "devuser"
    command: ["sleep", "infinity"]
    working_dir: /workspace/dlomix-serving
    volumes:
     - .:/workspace/dlomix-serving:Z
    depends_on:
      serving:
        condition: service_healthy
    env_file:
     - .env

  reverse-proxy:
    image: nginx
    depends_on:
      serving:
          condition: service_healthy
    ports:
      - 8502:8502
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    command: [nginx-debug, '-g', 'daemon off;']

  swagger_gen:
    build:
      context: .
      target: swagger-gen
    depends_on: 
      serving:
        condition: service_healthy
    environment:
      TRITON_SERVER_IP: "10.152.171.77"
    volumes:
      - ./:/workspace
    command:
      - /bin/sh
      - -c
      - |
        cd /workspace/swagger
        python swagger_gen.py

  swagger:
    build:
      context: .
      target: swagger-dlomix
    ports:
      - 8080:8080
    depends_on:
      swagger_gen:
        condition: service_completed_successfully
    volumes:
      - ./:/workspace