services:
  ludwig:
    build:
        context: .
    command: #nvidia-smi
        tritonserver
        --model-store=/models/AlphaPept
        --allow-grpc=true
        --grpc-port=8500
        --allow-http=true
        --http-port=8501
        --log-info=true
        --log-warning=true
        --log-error=true
    ports:
      - 8504:8500
      - 8505:8501
    volumes:
      - ./models:/models
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    environment:
      CUDA_VISIBLE_DEVICES: 0
    shm_size: 1GB
