services:
  serving:
    build:
      context: .
      target: develop
    user: "${UID}:${GID}"
    volumes:
      - ./models:/models:z
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ["${GPU_DEVICE}"]
              capabilities: [ gpu ]
    shm_size: 2GB
    restart: unless-stopped

  develop:
    build:
      context: .
      target: util
      args:
        UID: ${UID}
        GID: ${GID}
    user: "devuser"
    command: [ "sleep", "infinity" ]
    working_dir: /workspace/koina
    volumes:
      - .:/workspace/koina/:z
    env_file:
      - .env

  web:
    build:
      context: .
      target: web
      args:
        UID: ${UID}
        GID: ${GID}
    ports:
      - 3000:3000
    volumes:
      - ./:/workspace/koina
    working_dir: /workspace/koina/web
    command: npm run dev
