services:
  serving:
    build:
      context: .
      target: develop
    command: /models/start_triton_server.sh
    ports:
      - 8504:8500
      - 8505:8501
    volumes:
      - ./models:/models
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    shm_size: 2GB

  develop:
    build:
     context: .
     target: util
     args:
      - UID=${UID}
      - GID=${GID}
    user: "devuser"
    command: ["sleep", "infinity"]
    working_dir: /workspace/dlomix-serving
    volumes:
     - .:/workspace/dlomix-serving:Z
