name: koina_${UID}
services:
  serving:
    build:
      context: .
      target: develop
    command: /models/start_triton_server.sh
    volumes:
      - ./models:/models
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['1']
              capabilities: [ gpu ]
    shm_size: 2GB
    restart: unless-stopped

  develop:
    build:
      context: .
      target: util
      args:
        UID: ${UID}
        GID: ${GID}
    user: "devuser"
    command: [ "sleep", "infinity" ]
    working_dir: /workspace/koina
    volumes:
      - .:/workspace/koina/:Z
    depends_on:
      serving:
        condition: service_healthy
    env_file:
      - .env

  web :
    build:
      context: .
      target: web
      args:
        UID: ${UID}
        GID: ${GID}
    ports:
      - 8503:3000
    volumes:
      - ./:/workspace/koina
    working_dir: /workspace/koina/web
    command: npm run dev
