services:
  serving1:
    image: nvcr.io/nvidia/tritonserver:22.09-py3
    container_name: triton_deeplc
    command: bash /models/start_triton_server.sh
    ports:
      - 8502:8500
      - 8503:8501
    volumes:
      - ./models:/models
    shm_size: 1GB
