services:
  serving1:
    build:
      context: .
    command: bash /models/start_triton_server.sh
    ports:
      - 8502:8500
      - 8503:8501
    volumes:
      - ./models:/models
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    shm_size: 2GB
