services:
  dev:
    build:
      context: .
      target: develop
    command: /models/start_triton_server.sh
    ports:
      - 8500:8500
      - 8501:8501
    volumes:
      - ./models:/models
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    shm_size: 2GB

  test:
    build:
     context: .
     target: test
    volumes:
      - ./test:/test
    depends_on:
      dev:
        condition: service_healthy
