openapi: 3.0.3
info:
  title: Swagger Triton Prosit model serving - OpenAPI 3.0
  description: |-
   This is a documentation for the machine learning models for proteomics DLomix
   There are multiple different models are hosted. Such as Prosit, MS2PIP and DeepLC
  termsOfService: http://swagger.io/terms/
  contact:
    email: apiteam@swagger.io
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.11
externalDocs:
  description: Find out more about Swagger
  url: http://swagger.io
servers:
  - url: http://{{triton_server_ip~':'~triton_server_port}}/v2/models

tags:
{% for model in models %}
  - name: {{model.note.tag}}
    description: {{model.note.tag_description }}
    externalDocs:
      description: Find out more
      url: {{model.note.tag_url}}
{% endfor %}
paths:
{% for model in models %}
  /{{model.name}}/infer:
     post:
      tags:
        - {{model.note.tag}}
      summary: {{model.note.summary}}
      description: |
              {{model.note.description }}
              {{model.note.code}}
      operationId: {{model.name}}
      requestBody:
        description: Body
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/{{model.name ~ '_' ~ 'input'}}'
          application/xml:
            schema:
              $ref: '#/components/schemas/{{model.name ~ '_' ~ 'input'}}'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/{{model.name ~ '_' ~ 'input'}}'
        required: true
      responses:
        '200':
          description: Successful operation
        '405':
          description: Invalid input
{% endfor %}

components:
  schemas:
    parameters:
      type: object
      properties:
        sequence_id:
          type: integer
          example: 0
        sequence_start:
          type: boolean
          example: false
        sequence_end:
          type: boolean
          example: false

{% for model in models %}
    {{model.name ~ '_' ~ 'input'}}:
      type: object
      properties:
        id:
          type: string
          example: "it_can_be_anything"
        inputs:
          type: array
          example: {{ model.note['examples']['input'] }}
          items:
            allOf:
              {% for input in model.input %}
              - $ref: "#/components/schemas/{{model.name ~ '_' ~ 'input_'~input.name}}"
              {% endfor %}
        
  {% for input in model.input %}
    {{model.name ~ '_' ~ 'input_'~input.name}}:
      type: object
      properties:
        name:
          type: string
        shape:
          type: array
          items:
            type: integer
        datatype:
          type: string
        data:
          type: array
          items:
            type: string
  {% endfor %}
{% endfor %}