---

- name: install lambda
  hosts: all
  gather_facts: true
  become: yes
  tasks:
  - name: Install kernel headers
    apt:
      update_cache: true
      name: linux-headers-generic
  - name: Install lambda stack (takes a while)
    ansible.builtin.shell:
      cmd: |
            wget -nv -O- https://lambdalabs.com/install-lambda-stack.sh | I_AGREE_TO_THE_CUDNN_LICENSE=1 sh -

- name: Install nvidia container toolkit
  hosts: all
  become: yes
  tasks:
    - name: install packages
      apt: name={{item}} update_cache=yes
      with_items:
        - docker.io
        - nvidia-container-toolkit

- name: Reboot machine
  hosts: all
  become: yes
  tasks:
    - name: reboot it
      reboot:
        msg: "Reboot initiated by Ansible"
        connect_timeout: 5
        reboot_timeout: 600
        pre_reboot_delay: 0
        post_reboot_delay: 30
        test_command: whoami
