name: Run tests, styling and linting

on:
  pull_request:

jobs:

  mergeCI:
    runs-on: [self-hosted,Linux,X64,gpu]
    permissions:
      contents: read
   
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Start service
        run: docker compose up -d serving develop --build

      - name: Wait for serving startup
        run: sleep 60

      - name: Pytest
        run: docker compose exec develop pytest

      - name: Verify code style
        run: docker compose exec develop black .

      - name: Run lint
        run: docker compose exec develop lint --fail-under=6

      - name: Shutdown service
        if: success() || failure()
        run: docker compose down
        
      - name: Remove container
        if: success() || failure()
        run: docker compose rm
