name: Run tests, styling and linting

on:
  pull_request:

jobs:

  mergeCI:
    runs-on: [self-hosted,Linux,X64,gpu]
    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Startup
        run: docker-compose --env-file .env.ci up -d --build serving develop

      - name: Wait for poetry install
        run: sleep 60

      - name: Styling
        run: docker-compose --env-file .env.ci exec develop koina_format.sh

      - name: Linting
        run: docker-compose --env-file .env.ci exec develop koina_lint.sh --fail-under=6

      - name: Testing
        run: docker-compose --env-file .env.ci exec develop koina_test.sh --check

      - name: Shutdown
        if: always()
        run: docker-compose --env-file .env.ci down

      - name: Cleanup
        if: always()
        run: docker-compose --env-file .env.ci rm
