name: Run tests, styling and linting

on:
  pull_request:

jobs:

  mergeCI:
    runs-on: [self-hosted,Linux,X64,gpu]
    permissions:
      contents: read
   
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Start
        run: docker compose --env-file .env.ci up -d serving develop --build

      - name: Styling
        run: docker compose exec develop black .

      - name: Linting
        run: docker compose exec develop koina_lint.sh --fail-under=6

      - name: Testing
        run: docker compose exec develop koina_test.sh

      - name: Shutdown
        if: success() || failure()
        run: docker compose down
        
      - name: Cleanup
        if: success() || failure()
        run: docker compose rm
