name: Build and publish Koina UI

on:
  pull_request:

jobs:

  release:
    runs-on: [self-hosted,Linux,X64,gpu]
    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Startup
        run: docker compose --env-file .env.ci up -d serving develop web --build

      - name: Install npm dependencies
        run: docker compose --env-file .env.ci exec web npm install

      - name: Wait for serving
        run: docker compose --env-file .env.ci exec develop koina_test.sh

      - name: Update OpenAPI
        run: docker compose --env-file .env.ci exec develop python web/openapi/openapi_gen.py 

      - name: Build UI
        run: docker compose --env-file .env.ci exec web npm generate

      - name: Copy folder content recursively to remote
        uses: garygrossgarten/github-action-scp@release
        with:
          local: web/.output/public
          remote: /var/www/koina/
          host: ${{ secrets.WEBSERVER }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.PASSWORD }}

      - name: Shutdown
        if: success() || failure()
        run: docker compose --env-file .env.ci down
        
      - name: Cleanup
        if: success() || failure()
        run: docker compose --env-file .env.ci rm


